create table users (
    id int8 generated by default as identity,
    starting_price float8,
    username varchar(255),
    cryptocurrency_id int8,
    primary key (id)
);
alter table if exists users add constraint UK_username unique (username);
alter table if exists users add constraint FK_cryptocurrencies_users foreign key (cryptocurrency_id) references cryptocurrencies;